name: think_tanker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: null
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  get: null
  google_fonts: null
  google_sign_in: ^6.0.2
  intl: null
  lottie: ^2.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
